create table if not exists public.clients (
  id uuid primary key default gen_random_uuid(),
  business_id uuid not null references public.businesses(id) on delete cascade,
  name text not null,
  phone text not null,
  email text,
  notes text,
  loyalty_points integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.appointments (
  id uuid primary key default gen_random_uuid(),
  appointment_number integer generated by default as identity,
  business_id uuid not null references public.businesses(id) on delete cascade,
  client_id uuid references public.clients(id) on delete set null,
  client_name text not null,
  client_phone text not null,
  professional_id uuid references public.professionals(id) on delete set null,
  requested_date date not null,
  requested_time time not null,
  status text not null default 'requested',
  notes text,
  subtotal integer not null default 0,
  deposit_required boolean not null default false,
  deposit_amount integer not null default 0,
  deposit_status text not null default 'not_required',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.appointment_services (
  id uuid primary key default gen_random_uuid(),
  appointment_id uuid not null references public.appointments(id) on delete cascade,
  service_id uuid references public.services(id) on delete set null,
  service_name text not null,
  price_from integer not null default 0,
  duration_minutes integer not null default 30,
  created_at timestamptz not null default now()
);

alter table public.clients enable row level security;
alter table public.appointments enable row level security;
alter table public.appointment_services enable row level security;

create policy clients_insert_public on public.clients for insert with check (true);
create policy appointments_insert_public on public.appointments for insert with check (true);
create policy appointment_services_insert_public on public.appointment_services for insert with check (true);
