create table if not exists public.catalog_items (
  id uuid primary key default gen_random_uuid(),
  business_id uuid not null references public.businesses(id) on delete cascade,
  kind text not null default 'service',
  name text not null,
  description text,
  category text,
  price integer not null default 0,
  duration_minutes integer,
  requires_deposit boolean not null default false,
  deposit_amount integer not null default 0,
  image_url text,
  is_active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.transactions (
  id uuid primary key default gen_random_uuid(),
  transaction_number integer generated by default as identity,
  business_id uuid not null references public.businesses(id) on delete cascade,
  client_id uuid references public.client_profiles(id) on delete set null,
  type text not null default 'booking',
  status text not null default 'pending',
  payment_method text not null default 'sinpe',
  payment_status text not null default 'pending',
  payment_verified boolean not null default false,
  receipt_url text,
  subtotal integer not null default 0,
  discount_amount integer not null default 0,
  total integer not null default 0,
  coupon_code text,
  promotion_id uuid references public.promotions(id) on delete set null,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.transaction_items (
  id uuid primary key default gen_random_uuid(),
  transaction_id uuid not null references public.transactions(id) on delete cascade,
  catalog_item_id uuid references public.catalog_items(id) on delete set null,
  name text not null,
  kind text not null default 'service',
  quantity integer not null default 1,
  unit_price integer not null default 0,
  total integer not null default 0,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.memberships (
  id uuid primary key default gen_random_uuid(),
  business_id uuid not null references public.businesses(id) on delete cascade,
  client_id uuid not null references public.client_profiles(id) on delete cascade,
  plan_name text not null,
  amount integer not null default 0,
  status text not null default 'active',
  current_period_start date,
  current_period_end date,
  last_payment_transaction_id uuid references public.transactions(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.catalog_items enable row level security;
alter table public.transactions enable row level security;
alter table public.transaction_items enable row level security;
alter table public.memberships enable row level security;

create policy catalog_items_public_read on public.catalog_items for select using (is_active = true);
create policy transactions_insert_public on public.transactions for insert with check (true);
create policy transaction_items_insert_public on public.transaction_items for insert with check (true);
create policy memberships_public_read on public.memberships for select using (true);
